name: build

on:
  push:
    branches:
    - dev
    - main
  schedule:
  - cron: '30 12 * * 3'
  workflow_dispatch:

jobs:
  arm64:
    runs-on: arvato
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
    - name: Login to GitHub Packages Docker Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and Push Latest
      uses: docker/build-push-action@v6
      if: github.ref == 'refs/heads/main'
      with:
        push: true
        pull: true
        tags: ghcr.io/arvatoaws-labs/kubernetes-worker:latest-arm64
        cache-from: type=registry,ref=ghcr.io/arvatoaws-labs/kubernetes-worker:latest-arm64
        cache-to: type=inline
    - name: Build and Push Dev
      uses: docker/build-push-action@v6
      if: github.ref == 'refs/heads/dev'
      with:
        push: true
        pull: true
        tags: ghcr.io/arvatoaws-labs/kubernetes-worker:dev-arm64
        cache-from: type=registry,ref=ghcr.io/arvatoaws-labs/kubernetes-worker:dev-arm64
        cache-to: type=inline
  amd64:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
    - name: Login to GitHub Packages Docker Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and Push Latest
      uses: docker/build-push-action@v6
      if: github.ref == 'refs/heads/main'
      with:
        push: true
        pull: true
        tags: ghcr.io/arvatoaws-labs/kubernetes-worker:latest-amd64
        cache-from: type=registry,ref=ghcr.io/arvatoaws-labs/kubernetes-worker:latest-amd64
        cache-to: type=inline
    - name: Build and Push Dev
      uses: docker/build-push-action@v6
      if: github.ref == 'refs/heads/dev'
      with:
        push: true
        pull: true
        tags: ghcr.io/arvatoaws-labs/kubernetes-worker:dev-amd64
        cache-from: type=registry,ref=ghcr.io/arvatoaws-labs/kubernetes-worker:dev-amd64
        cache-to: type=inline
  manifest:
    runs-on: arvato
    needs: [arm64, amd64]
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
    - name: Login to GitHub Packages Docker Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Merge manifests Latest
      if: github.ref == 'refs/heads/main'
      run: |
        set -x
        echo "Merging manifests"
        docker manifest create "ghcr.io/arvatoaws-labs/kubernetes-worker:latest" "ghcr.io/arvatoaws-labs/kubernetes-worker:latest-arm64" "ghcr.io/arvatoaws-labs/kubernetes-worker:latest-amd64"
        docker manifest annotate --arch arm64 "ghcr.io/arvatoaws-labs/kubernetes-worker:latest" "ghcr.io/arvatoaws-labs/kubernetes-worker:latest-arm64"
        docker manifest annotate --arch amd64 "ghcr.io/arvatoaws-labs/kubernetes-worker:latest" "ghcr.io/arvatoaws-labs/kubernetes-worker:latest-amd64"
        docker manifest push "ghcr.io/arvatoaws-labs/kubernetes-worker:latest"
    - name: Merge manifests Dev
      if: github.ref == 'refs/heads/dev'
      run: |
        set -x
        echo "Merging manifests"
        docker manifest create "ghcr.io/arvatoaws-labs/kubernetes-worker:dev" "ghcr.io/arvatoaws-labs/kubernetes-worker:dev-arm64" "ghcr.io/arvatoaws-labs/kubernetes-worker:dev-amd64"
        docker manifest annotate --arch arm64 "ghcr.io/arvatoaws-labs/kubernetes-worker:dev" "ghcr.io/arvatoaws-labs/kubernetes-worker:dev-arm64"
        docker manifest annotate --arch amd64 "ghcr.io/arvatoaws-labs/kubernetes-worker:dev" "ghcr.io/arvatoaws-labs/kubernetes-worker:dev-amd64"
        docker manifest push "ghcr.io/arvatoaws-labs/kubernetes-worker:dev"
