name: build

on:
  push:
    branches:
    - dev
    - main
  schedule:
  - cron: '30 12 * * 3'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    # - name: What
    #   run: echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      with:
        platforms: all
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2
      with:
        install: true
        version: latest
        driver-opts: image=moby/buildkit:master
    - name: Login to GitHub Packages Docker Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: jenkins-arvato
        password: ${{ secrets.CR_PAT }}
    - name: Build and Push Latest
      uses: docker/build-push-action@v5
      if: github.ref == 'refs/heads/main'
      with:
        platforms: linux/amd64,linux/arm64
        push: true
        pull: true
        tags: ghcr.io/arvatoaws-labs/kubernetes-worker:latest
        cache-from: type=registry,ref=ghcr.io/arvatoaws-labs/kubernetes-worker:latest
        cache-to: type=inline
    - name: Build and Push Dev
      uses: docker/build-push-action@v5
      if: github.ref == 'refs/heads/dev'
      with:
        platforms: linux/amd64,linux/arm64
        push: true
        pull: true
        tags: ghcr.io/arvatoaws-labs/kubernetes-worker:dev
        cache-from: type=registry,ref=ghcr.io/arvatoaws-labs/kubernetes-worker:dev
        cache-to: type=inline